### ISSUE TITLE
Kernel dies with inline-r or maybe TemplateHaskell or QuasiQuotes

### ISSUE THREAD

**Issue by idontgetoutmuch** [gibiansky/IHaskell#1077]
bash-3.2$ nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz release-8.6.nix --arg packages "haskellPackages: [ haskellPackages.inline-r ]"

![image](https://user-images.githubusercontent.com/1550265/61861726-6e5e2f00-aec4-11e9-8269-f05f3c61e43d.png)

```
bash-3.2$ /nix/store/x5a6dxgsv7ry0cr8gj2q5a9jc37naf5k-ihaskell-with-packages/bin/ihaskell-notebook
[I 08:09:41.205 NotebookApp] JupyterLab extension loaded from /nix/store/ny8p0l9hm8gwcsp2fd3f2d8cwqchbplb-python3-3.7.4-env/lib/python3.7/site-packages/jupyterlab
[I 08:09:41.205 NotebookApp] JupyterLab application directory is /nix/store/gq2ckky2yvibw0yag1yb1kwzfv5vbaff-python3.7-jupyterlab-0.35.4/share/jupyter/lab
[W 08:09:41.208 NotebookApp] Error loading server extension nbdime
    Traceback (most recent call last):
      File "/nix/store/ny8p0l9hm8gwcsp2fd3f2d8cwqchbplb-python3-3.7.4-env/lib/python3.7/site-packages/notebook/notebookapp.py", line 1572, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/nix/store/ny8p0l9hm8gwcsp2fd3f2d8cwqchbplb-python3-3.7.4-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'nbdime'
[I 08:09:41.209 NotebookApp] Serving notebooks from local directory: /Users/dom/IHaskell
[I 08:09:41.209 NotebookApp] The Jupyter Notebook is running at:
[I 08:09:41.209 NotebookApp] http://localhost:8888/?token=03dadc502fe7ed2d67886524439104914cb134ba7f9fdd1a
[I 08:09:41.217 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:09:41.237 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/dom/Library/Jupyter/runtime/nbserver-11996-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=03dadc502fe7ed2d67886524439104914cb134ba7f9fdd1a
[I 08:10:14.526 NotebookApp] Kernel started: 23fa1b9c-1d43-4eb2-b1e2-94b049c18c15
[W 08:10:14.543 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20190725080940 (::1) 12.51ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
[W 08:10:14.592 NotebookApp] 404 POST /nbdime/api/isgit (::1) 1.56ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
[W 08:10:14.603 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190725080940 (::1) 1.50ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
[I 08:10:15.497 NotebookApp] Adapting to protocol v5.0 for kernel 23fa1b9c-1d43-4eb2-b1e2-94b049c18c15
[I 08:10:23.526 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 23fa1b9c-1d43-4eb2-b1e2-94b049c18c15 restarted
[I 08:12:15.522 NotebookApp] Saving file at /Untitled1.ipynb
```

See also https://github.com/gibiansky/IHaskell/issues/965 and https://github.com/gibiansky/IHaskell/issues/236.

**Comment by vaibhavsagar** [comment]
Again, does this work with GHCi?

```
[vaibhavsagar@nixos:~/repos/IHaskell]$ nix-shell -p 'haskellPackages.ghcWithPackages (p: [ p.inline-r ])'
<...>
[nix-shell:~/repos/IHaskell]$ ghci
GHCi, version 8.6.4: http://www.haskell.org/ghc/  :? for help
package flags have changed, resetting and loading new packages...
cannot satisfy -package ghc-paths
    (use -v for more information)
Loaded GHCi configuration from /home/vaibhavsagar/repos/IHaskell/.ghci
λ> :set -XTemplateHaskell
λ> :set -XQuasiQuotes
λ> import qualified Language.R as R
λ> import Language.R.QQ
λ> :t [r| print(df_hs) |]

<interactive>:1:1: error:
    • Exception when trying to run compile-time code:
        R: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
      Code: Language.Haskell.TH.Quote.quoteExp r " print(df_hs) "
    • In the quasi-quotation: [r| print(df_hs) |]
```

**Comment by idontgetoutmuch** [comment]
Ah it needs R

**Comment by idontgetoutmuch** [comment]
[nix-shell:~/nixtest]$ ghci -fno-ghci-sandbox
GHCi, version 8.6.4: http://www.haskell.org/ghc/  :? for help
Prelude> :set -XTemplateHaskell
Prelude> :set -XQuasiQuotes
Prelude> import qualified Language.R as R
Prelude R> import Language.R.QQ
Prelude R> (R.runRegion $ do _ <- [r| print(pi) |]; return ())
Prelude R Language.R.QQ> (R.runRegion $ do _ <- [r| print(pi) |]; return ())
[1] 3.141593

**Comment by idontgetoutmuch** [comment]
`shell.nix`

```
{ nixpkgs ? import ./nix/nixpkgs.nix {} }:

let
  inherit (nixpkgs) pkgs;
  inherit (pkgs) haskellPackages;

  haskellDeps = ps: with ps; [
    inline-r
  ];

  ghc = haskellPackages.ghcWithPackages haskellDeps;

  nixPackages = [
    ghc
    pkgs.R
  ];
in
pkgs.stdenv.mkDerivation {
  name = "env";
  buildInputs = nixPackages;
}
```

'nixpkgs.nix`

```
{ system ? builtins.currentSystem }:
let
  nixpkgs = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz";
    sha256 = "06cqc37yj23g3jbwvlf9704bl5dg8vrzqvs5y2q18ayg9sw61i6z";
  };
in
  import nixpkgs {
    inherit system;
    config = {}; # prevent nixpkgs from loading user configuration
    overlays = [ (import ./overlay.nix) ];
  }
```

`overlay.nix`

```
self: super:

let haskellOverlay = hself: hsuper: {
  inline-r = self.haskell.lib.dontCheck (super.haskellPackages.inline-r);
};

in

{
  haskellPackages = super.haskellPackages.override { overrides = haskellOverlay; };
}
```

**Comment by idontgetoutmuch** [comment]
![image](https://user-images.githubusercontent.com/1550265/61964803-ab124f00-afc6-11e9-836c-cd0b29171f32.png)

**Comment by vaibhavsagar** [comment]
Template Haskell works just fine in an IHaskell notebook, that's not what's going on here

**Comment by vaibhavsagar** [comment]
Here's what I see:
![](https://user-images.githubusercontent.com/1525767/61970671-472e5d00-afab-11e9-9ae7-3b882eae5e3f.png)

**Comment by idontgetoutmuch** [comment]
What nix expression are you using? The same as mine?

**Comment by idontgetoutmuch** [comment]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/1550265/61970943-b8830580-afd5-11e9-8905-0493e36e8b37.png">

**Comment by vaibhavsagar** [comment]
I updated my comment with the Nix expression I'm using. I have it saved as `foo.nix` and am running it with `nix-build foo.nix`.

**Comment by idontgetoutmuch** [comment]
![image](https://user-images.githubusercontent.com/1550265/61972259-136a2c00-afd9-11e9-934e-8a07f27b8302.png)

**Comment by vaibhavsagar** [comment]
![](https://user-images.githubusercontent.com/1525767/61972849-9dea6580-afb0-11e9-8c4f-ee6fcad40772.png)

**Comment by vaibhavsagar** [comment]
Closing, please reopen if necessary.

**Comment by idontgetoutmuch** [comment]
If you are on macOS don't forget `:set -fno-ghci-sandbox`.
