### ISSUE TITLE
Extension not working in 1.1.1

### ISSUE THREAD

**Issue by daviddavo** [gibiansky/IHaskell#1108]
```
➜  ~ jupyter labextension install ihaskell_jupyterlab
An error occured.
KeyError: '@jupyterlab/apputils'
See the log file for details:  /tmp/jupyterlab-debug-tiggqax5.log
➜  ~ jupyter --version
jupyter core     : 4.6.0
jupyter-notebook : 6.0.1
qtconsole        : not installed
ipython          : not installed
ipykernel        : 5.1.1
jupyter client   : 5.3.4
jupyter lab      : 1.1.1
nbconvert        : 5.6.0
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.2
```

The log says:
```
Node v12.9.1

> /usr/bin/npm pack ihaskell_jupyterlab
npm notice 
npm notice 📦  ihaskell_jupyterlab@0.0.6
npm notice === Tarball Contents === 
npm notice 1.2kB package.json                
npm notice 466B  README.md                   
npm notice 78B   lib/codemirror-ihaskell.d.ts
npm notice 837B  lib/codemirror-ihaskell.js  
npm notice 257B  lib/index.d.ts              
npm notice 506B  lib/index.js                
npm notice 0     style/index.css             
npm notice === Tarball Details === 
npm notice name:          ihaskell_jupyterlab                     
npm notice version:       0.0.6                                   
npm notice filename:      ihaskell_jupyterlab-0.0.6.tgz           
npm notice package size:  1.6 kB                                  
npm notice unpacked size: 3.4 kB                                  
npm notice shasum:        8233d1b1a94212c9ccaf424762f033fdc051b412
npm notice integrity:     sha512-t9LSmG3MqMJco[...]MUtkNnwOSUxgw==
npm notice total files:   7                                       
npm notice 
ihaskell_jupyterlab-0.0.6.tgz

Fetching URL: https://registry.npmjs.org/ihaskell_jupyterlab
Fetching URL: https://registry.npmjs.org/ihaskell_jupyterlab
Traceback (most recent call last):

  File "/usr/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/usr/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/usr/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 321, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 525, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 1446, in _install_extension
    self._format_no_compatible_package_version(name),

  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 1619, in _format_no_compatible_package_version
    c = _compare_ranges(core_deps[key], value)

KeyError: '@jupyterlab/apputils'

Exiting application: jupyter
```

**Comment by vaibhavsagar** [comment]
This is what I got:
```bash
[nix-shell:~/code/experiments]$ npm pack @jupyterlab/apputils
npm notice 
npm notice 📦  @jupyterlab/apputils@1.1.3
npm notice === Tarball Contents === 
npm notice 1.8kB  package.json             
npm notice 1.7kB  LICENSE                  
npm notice 156B   README.md                
npm notice 12.8kB lib/clientsession.d.ts   
npm notice 27.9kB lib/clientsession.js     
npm notice 21.7kB lib/clientsession.js.map 
npm notice 955B   lib/clipboard.d.ts       
npm notice 2.7kB  lib/clipboard.js         
npm notice 1.9kB  lib/clipboard.js.map     
npm notice 1.8kB  lib/collapse.d.ts        
npm notice 3.9kB  lib/collapse.js          
npm notice 3.1kB  lib/collapse.js.map      
npm notice 4.2kB  lib/commandlinker.d.ts   
npm notice 5.9kB  lib/commandlinker.js     
npm notice 2.3kB  lib/commandlinker.js.map 
npm notice 943B   lib/commandpalette.d.ts  
npm notice 489B   lib/commandpalette.js    
npm notice 265B   lib/commandpalette.js.map
npm notice 10.7kB lib/dialog.d.ts          
npm notice 18.2kB lib/dialog.js            
npm notice 12.8kB lib/dialog.js.map        
npm notice 713B   lib/domutils.d.ts        
npm notice 1.3kB  lib/domutils.js          
npm notice 970B   lib/domutils.js.map      
npm notice 2.8kB  lib/hoverbox.d.ts        
npm notice 4.2kB  lib/hoverbox.js          
npm notice 3.3kB  lib/hoverbox.js.map      
npm notice 2.7kB  lib/iframe.d.ts          
npm notice 2.7kB  lib/iframe.js            
npm notice 1.9kB  lib/iframe.js.map        
npm notice 643B   lib/index.d.ts           
npm notice 779B   lib/index.js             
npm notice 602B   lib/index.js.map         
npm notice 3.4kB  lib/inputdialog.d.ts     
npm notice 7.4kB  lib/inputdialog.js       
npm notice 5.8kB  lib/inputdialog.js.map   
npm notice 3.5kB  lib/mainareawidget.d.ts  
npm notice 6.5kB  lib/mainareawidget.js    
npm notice 5.4kB  lib/mainareawidget.js.map
npm notice 1.9kB  lib/printing.d.ts        
npm notice 5.6kB  lib/printing.js          
npm notice 3.2kB  lib/printing.js.map      
npm notice 1.1kB  lib/sanitizer.d.ts       
npm notice 44.1kB lib/sanitizer.js         
npm notice 32.6kB lib/sanitizer.js.map     
npm notice 353B   lib/spinner.d.ts         
npm notice 839B   lib/spinner.js           
npm notice 578B   lib/spinner.js.map       
npm notice 535B   lib/splash.d.ts          
npm notice 313B   lib/splash.js            
npm notice 260B   lib/splash.js.map        
npm notice 817B   lib/styling.d.ts         
npm notice 2.8kB  lib/styling.js           
npm notice 2.2kB  lib/styling.js.map       
npm notice 4.6kB  lib/thememanager.d.ts    
npm notice 12.7kB lib/thememanager.js      
npm notice 9.2kB  lib/thememanager.js.map  
npm notice 2.5kB  lib/tokens.d.ts          
npm notice 317B   lib/tokens.js            
npm notice 260B   lib/tokens.js.map        
npm notice 7.1kB  lib/toolbar.d.ts         
npm notice 18.4kB lib/toolbar.js           
npm notice 10.5kB lib/toolbar.js.map       
npm notice 5.5kB  lib/vdom.d.ts            
npm notice 5.3kB  lib/vdom.js              
npm notice 3.2kB  lib/vdom.js.map          
npm notice 8.3kB  lib/widgettracker.d.ts   
npm notice 7.0kB  lib/widgettracker.js     
npm notice 3.3kB  lib/widgettracker.js.map 
npm notice 1.1kB  lib/windowresolver.d.ts  
npm notice 5.3kB  lib/windowresolver.js    
npm notice 3.0kB  lib/windowresolver.js.map
npm notice 546B   style/base.css           
npm notice 1.1kB  style/collapse.css       
npm notice 5.4kB  style/commandpalette.css 
npm notice 2.3kB  style/dialog.css         
npm notice 363B   style/hoverbox.css       
npm notice 838B   style/iframe.css         
npm notice 480B   style/index.css          
npm notice 324B   style/mainareawidget.css 
npm notice 7.3kB  style/materialcolors.css 
npm notice 1.4kB  style/spinner.css        
npm notice 2.3kB  style/styling.css        
npm notice 2.3kB  style/toolbar.css        
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/apputils                    
npm notice version:       1.1.3                                   
npm notice filename:      jupyterlab-apputils-1.1.3.tgz           
npm notice package size:  85.4 kB                                 
npm notice unpacked size: 420.3 kB                                
npm notice shasum:        697f3fccf4d5e6a5b4541d772c755e9a31bdcc29
npm notice integrity:     sha512-5kTmNSNedP+Fy[...]41Uk7HrQ0TKCA==
npm notice total files:   84                                      
npm notice 
jupyterlab-apputils-1.1.3.tgz
```

Can you try again please?

**Comment by daviddavo** [comment]
I get the same as you, but when I'm using jupyter it doesn't seem to work
```
➜  ~ npm pack @jupyterlab/apputils
npm notice 
npm notice 📦  @jupyterlab/apputils@1.1.3
npm notice === Tarball Contents === 
npm notice 1.8kB  package.json             
npm notice 1.7kB  LICENSE                  
npm notice 156B   README.md                
npm notice 12.8kB lib/clientsession.d.ts   
npm notice 27.9kB lib/clientsession.js     
npm notice 21.7kB lib/clientsession.js.map 
npm notice 955B   lib/clipboard.d.ts       
npm notice 2.7kB  lib/clipboard.js         
npm notice 1.9kB  lib/clipboard.js.map     
npm notice 1.8kB  lib/collapse.d.ts        
npm notice 3.9kB  lib/collapse.js          
npm notice 3.1kB  lib/collapse.js.map      
npm notice 4.2kB  lib/commandlinker.d.ts   
npm notice 5.9kB  lib/commandlinker.js     
npm notice 2.3kB  lib/commandlinker.js.map 
npm notice 943B   lib/commandpalette.d.ts  
npm notice 489B   lib/commandpalette.js    
npm notice 265B   lib/commandpalette.js.map
npm notice 10.7kB lib/dialog.d.ts          
npm notice 18.2kB lib/dialog.js            
npm notice 12.8kB lib/dialog.js.map        
npm notice 713B   lib/domutils.d.ts        
npm notice 1.3kB  lib/domutils.js          
npm notice 970B   lib/domutils.js.map      
npm notice 2.8kB  lib/hoverbox.d.ts        
npm notice 4.2kB  lib/hoverbox.js          
npm notice 3.3kB  lib/hoverbox.js.map      
npm notice 2.7kB  lib/iframe.d.ts          
npm notice 2.7kB  lib/iframe.js            
npm notice 1.9kB  lib/iframe.js.map        
npm notice 643B   lib/index.d.ts           
npm notice 779B   lib/index.js             
npm notice 602B   lib/index.js.map         
npm notice 3.4kB  lib/inputdialog.d.ts     
npm notice 7.4kB  lib/inputdialog.js       
npm notice 5.8kB  lib/inputdialog.js.map   
npm notice 3.5kB  lib/mainareawidget.d.ts  
npm notice 6.5kB  lib/mainareawidget.js    
npm notice 5.4kB  lib/mainareawidget.js.map
npm notice 1.9kB  lib/printing.d.ts        
npm notice 5.6kB  lib/printing.js          
npm notice 3.2kB  lib/printing.js.map      
npm notice 1.1kB  lib/sanitizer.d.ts       
npm notice 44.1kB lib/sanitizer.js         
npm notice 32.6kB lib/sanitizer.js.map     
npm notice 353B   lib/spinner.d.ts         
npm notice 839B   lib/spinner.js           
npm notice 578B   lib/spinner.js.map       
npm notice 535B   lib/splash.d.ts          
npm notice 313B   lib/splash.js            
npm notice 260B   lib/splash.js.map        
npm notice 817B   lib/styling.d.ts         
npm notice 2.8kB  lib/styling.js           
npm notice 2.2kB  lib/styling.js.map       
npm notice 4.6kB  lib/thememanager.d.ts    
npm notice 12.7kB lib/thememanager.js      
npm notice 9.2kB  lib/thememanager.js.map  
npm notice 2.5kB  lib/tokens.d.ts          
npm notice 317B   lib/tokens.js            
npm notice 260B   lib/tokens.js.map        
npm notice 7.1kB  lib/toolbar.d.ts         
npm notice 18.4kB lib/toolbar.js           
npm notice 10.5kB lib/toolbar.js.map       
npm notice 5.5kB  lib/vdom.d.ts            
npm notice 5.3kB  lib/vdom.js              
npm notice 3.2kB  lib/vdom.js.map          
npm notice 8.3kB  lib/widgettracker.d.ts   
npm notice 7.0kB  lib/widgettracker.js     
npm notice 3.3kB  lib/widgettracker.js.map 
npm notice 1.1kB  lib/windowresolver.d.ts  
npm notice 5.3kB  lib/windowresolver.js    
npm notice 3.0kB  lib/windowresolver.js.map
npm notice 546B   style/base.css           
npm notice 1.1kB  style/collapse.css       
npm notice 5.4kB  style/commandpalette.css 
npm notice 2.3kB  style/dialog.css         
npm notice 363B   style/hoverbox.css       
npm notice 838B   style/iframe.css         
npm notice 480B   style/index.css          
npm notice 324B   style/mainareawidget.css 
npm notice 7.3kB  style/materialcolors.css 
npm notice 1.4kB  style/spinner.css        
npm notice 2.3kB  style/styling.css        
npm notice 2.3kB  style/toolbar.css        
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/apputils                    
npm notice version:       1.1.3                                   
npm notice filename:      jupyterlab-apputils-1.1.3.tgz           
npm notice package size:  85.4 kB                                 
npm notice unpacked size: 420.3 kB                                
npm notice shasum:        697f3fccf4d5e6a5b4541d772c755e9a31bdcc29
npm notice integrity:     sha512-5kTmNSNedP+Fy[...]41Uk7HrQ0TKCA==
npm notice total files:   84                                      
npm notice 
jupyterlab-apputils-1.1.3.tgz
```

**Comment by vaibhavsagar** [comment]
I am able to reproduce this, I think the version bounds are too tight. @MMesch do we need a new release?

**Comment by MMesch** [comment]
I think so, I'll check it out in the next days.

**Comment by MMesch** [comment]
I think it should work now. At least on jupyterlab 1.2.2, I didn't check all intermediate version.

https://www.npmjs.com/package/jupyterlab-ihaskell

**Comment by vaibhavsagar** [comment]
Thank you! Is there a way I can have access to make a new release so we don't have to ping you each time?

**Comment by MMesch** [comment]
I wrote you a private message

**Comment by vaibhavsagar** [comment]
@daviddavo does this fix your issue?

**Comment by daviddavo** [comment]
Yes, It's working perfectly!

**Comment by vaibhavsagar** [comment]
Great! I am closing this.
