### ISSUE TITLE
error starting kernel:

### ISSUE THREAD

**Issue by zeta-00** [gibiansky/IHaskell#1132]
Traceback (most recent call last):
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/nix/store/a3r2kbzmz333bm707ssjfd2c0y5s0x69-python3-3.7.5-env/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell': '/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell'

**Comment by zeta-00** [comment]
after placing: (setq ein:polymode t) in my .emacs, i finally got past that kernel spec haskell not supported error, but now i am getting the error: session not found, and it stays stuck on kernel reconnecting, when i ran jupyter lab it opened in my browser(firefox), but when i clicked on haskell, it threw this nix store, errors, i am guessing the haskell kernel is not running because ihaskell is not even detected, i have ihaskell installed in home.nix, anyways i have no idea what is wrong and how to fix it?

**Comment by zeta-00** [comment]
# ihaskell package installation:
      (lib.lowPrio
      (let ihaskell = pkgs.fetchFromGitHub {
        owner = "gibiansky";
        repo = "IHaskell";
        rev = "2318ee2a90cfc98390651657aec434586b963235";
        sha256 = "0svjzs81i77s710cfb7pxkfdi979mhjazpc2l9k9ha752spz04cj";
      };
       in import "${ihaskell}/release.nix" {
                                             compiler = "ghc865";
                                             nixpkgs = pkgs;
                                             packages = self: with self; [];
					                                 }))
      # end of ihaskell package installation

**Comment by zeta-00** [comment]
i think nix is searching in the wrong directory for the ihaskell binary, but i am not sure why and how to fix it?

**Comment by vaibhavsagar** [comment]
How are you running IHaskell? The error output you have above is almost useless if you don't also include the command you ran to get that output.

**Comment by zeta-00** [comment]
ok, so basically I 1st opened a new notebook in emacs with the haskell kernel selected, the notebook opened but it stayed stuck in `kernel reconnecting`, 2nd, in emacs I pressed open in browser, which it then opened a jupyter web page in firefox, I pasted in the localhost:port_number web address and placed the generated token in the prompt, which then logged me in, when I select the drop down options: new notebook, haskell, the kernel error gets thrown: `failed to start kernel, unhandled error` , i already posted the error at the top of this issue, anyways in home.nix I installed ihaskell separately from ghcWithHoogle and the other haskell packages, in order to fix the collision error(between ghcWithHoogle and ihaskell) being thrown I set the option: `lib.lowPrio` in the ihaskell configuration, the collision error stopped and ihaskell got installed fine and it worked in the previous nixos stable version, but with this new nixos-stable channel 19.09 it stopped working, I could check with rycee to make sure it is not something having to do with home-manager, at this point i have no idea? I hope I was clear enough in all the steps that i did?

**Comment by zeta-00** [comment]
i think nix may looking in the wrong directory for the ihaskell binary, maybe that is why the haskell kernel is not being loaded, I tried out a python notebook and the python kernel works fine, so I just don't know?

**Comment by vaibhavsagar** [comment]
Does it work if you run it with `ihaskell-notebook`?

**Comment by zeta-00** [comment]
wow, that worked, i thought i would have to do something all complicated to get ihaskell working, and i didn't know i had to do that manually in the terminal to connect to the haskell kernel, now when i open an ihaskell notebook either in firefox or emacs the haskell kernel is loaded and ihaskell works. thanks for the help, and i would also like to thank you and the others behind ihaskell, it has greatly helped my haskell workflow and has made doing haskell coding much more enjoyable

**Comment by vaibhavsagar** [comment]
Glad I could help!
