### ISSUE TITLE
Module not found: Error: Can't resolve 'jupyterlab-ihaskell' 

### ISSUE THREAD

**Issue by adamsmd** [gibiansky/IHaskell#1211]
I'm having trouble installing the `jupyterlab-ihaskell` extension.  I spent an evening trying to figure this out but failed to do so.  Any ideas about how to fix this would be appriciated.

When I run `jupyter labextension install --log-level=DEBUG jupyterlab-ihaskell`, I get the following error.

```
ERROR in resolving fallback for shared module jupyterlab-ihaskell
Module not found: Error: Can't resolve 'jupyterlab-ihaskell' in '/home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/share/jupyter/lab/staging/build'
```

The complete output is as follows.  (The file `/tmp/jupyterlab-debug-_lnyugbm.log` contains the same except it doesn't have some of the lines at the start and end.)

```
Searching ['/home/adamsmd/o/jupyter/jupyter-pipenv', '/home/adamsmd/.jupyter', '/home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/etc/jupyter
Looking for jupyter_config in /home/adamsmd/.jupyter
Looking for jupyter_config in /home/adamsmd/o/jupyter/jupyter-pipenv
Looking for lab_config in /etc/jupyter
Looking for lab_config in /usr/local/etc/jupyter
Looking for lab_config in /home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/etc/jupyter
Looking for lab_config in /home/adamsmd/.jupyter
Looking for lab_config in /home/adamsmd/o/jupyter/jupyter-pipenv
Node v12.18.2

Yarn configuration loaded.
> /usr/bin/npm pack jupyterlab-ihaskell
npm notice 
npm notice 📦  jupyterlab-ihaskell@0.0.12
npm notice === Tarball Contents === 
npm notice 0     style/index.css
npm notice 1.2kB package.json   
npm notice 464B  README.md      
npm notice === Tarball Details === 
npm notice name:          jupyterlab-ihaskell                     
npm notice version:       0.0.12                                  
npm notice filename:      jupyterlab-ihaskell-0.0.12.tgz          
npm notice package size:  866 B                                   
npm notice unpacked size: 1.6 kB                                  
npm notice shasum:        2922b8d1c37b6376287744d97d2357ad228c5297
npm notice integrity:     sha512-FXE3KGNNRadi7[...]0FNX+8H/AalEg==
npm notice total files:   3                                       
npm notice 
jupyterlab-ihaskell-0.0.12.tgz

Fetching URL: https://registry.yarnpkg.com/jupyterlab-ihaskell
> /usr/bin/npm pack jupyterlab-ihaskell@0.0.12
npm notice 
npm notice 📦  jupyterlab-ihaskell@0.0.12
npm notice === Tarball Contents === 
npm notice 0     style/index.css
npm notice 1.2kB package.json   
npm notice 464B  README.md      
npm notice === Tarball Details === 
npm notice name:          jupyterlab-ihaskell                     
npm notice version:       0.0.12                                  
npm notice filename:      jupyterlab-ihaskell-0.0.12.tgz          
npm notice package size:  866 B                                   
npm notice unpacked size: 1.6 kB                                  
npm notice shasum:        2922b8d1c37b6376287744d97d2357ad228c5297
npm notice integrity:     sha512-FXE3KGNNRadi7[...]0FNX+8H/AalEg==
npm notice total files:   3                                       
npm notice 
jupyterlab-ihaskell-0.0.12.tgz

Node v12.18.2

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper@1.3.7" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 2.27s.

> node /home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.28s.

> node /home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
assets by status 10 MiB [cached] 114 assets
orphan modules 4.69 MiB [orphan] 1237 modules
runtime modules 99.3 KiB 14 modules
built modules 13.3 MiB (javascript) 4.47 KiB (consume-shared) 4.43 KiB (share-init) [built]
  modules by path ./node_modules/ 13.3 MiB
    cacheable modules 13.3 MiB 975 modules
    3 modules
  consume-shared-module modules 4.47 KiB
    modules by path consume shared module (default) @jupyterlab/ 3.53 KiB 41 modules
    modules by path consume shared module (default) @lumino/ 588 bytes 14 modules
  provide-module modules 4.43 KiB 108 modules
  modules by path ./build/ 23.3 KiB
    ./build/bootstrap.js 3.78 KiB [built] [code generated]
    ./build/index.out.js + 1 modules 19.5 KiB [built] [code generated]
  4 modules

WARNING in ./node_modules/vega-lite/build/src/index.js 5:0-30
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
 @ consume shared module (default) vega-lite@^4.0.2 (strict) (fallback: ./node_modules/vega-lite/build/src/index.js)
 @ ./node_modules/vega-embed/build/vega-embed.module.js 6:0-44 189:15-29
 @ consume shared module (default) vega-embed@^6.2.1 (strict) (fallback: ./node_modules/vega-embed/build/vega-embed.module.js)
 @ ./node_modules/@jupyterlab/vega5-extension/lib/index.js 166:28-48
 @ consume shared module (default) @jupyterlab/vega5-extension@~3.0.3 (strict) (fallback: ./node_modules/@jupyterlab/vega5-extension/lib/index.js)
 @ ./build/index.out.js 171:16-54
 @ ./build/bootstrap.js

ERROR in resolving fallback for shared module jupyterlab-ihaskell
Module not found: Error: Can't resolve 'jupyterlab-ihaskell' in '/home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/share/jupyter/lab/staging/build'

webpack 5.19.0 compiled with 1 error and 1 warning in 31788 ms

asset index.css 16.1 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 16.1 KiB = index.css 16.1 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-dark-extension/style/index.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/variables.css 15.3 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/base.css 472 bytes [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/index.css 342 bytes [code generated]
webpack 5.19.0 compiled successfully in 2060 ms

asset index.css 15 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 15 KiB = index.css 15 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-light-extension/style/index.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/variables.css 14.2 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/base.css 472 bytes [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/index.css 342 bytes [code generated]
webpack 5.19.0 compiled successfully in 2058 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 132, in start
    build(clean_staging=self.should_clean,

  File "/home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/lib/python3.8/site-packages/jupyterlab/commands.py", line 469, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/home/adamsmd/.local/share/virtualenvs/jupyter-pipenv-fwoNqfwc/lib/python3.8/site-packages/jupyterlab/commands.py", line 678, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-_lnyugbm.log
Exiting application: lab
```

**Comment by jamesdbrock** [comment]
Yeah the instructions about `jupyterlab-ihaskell` are obsolete. Please read https://github.com/gibiansky/IHaskell/issues/1202

**Comment by adamsmd** [comment]
Thank you for the pointer.  I'm using the latest `ihaskell` in Hackage and LTS, which seems to be from before that change.  I was hoping to avoid an unmanaged install of `ihaskell`, but it sounds like that might have to be what I do.
