### ISSUE TITLE
`jupyter execute` doesn't report errors

### ISSUE THREAD

**Issue by vaibhavsagar** [gibiansky/IHaskell#1315]
From https://github.com/gibiansky/IHaskell/issues/1227#issuecomment-1013598938:

```shell
vaibhavsagar@nixos-t480:~/repos/IHaskell$ cat Foo.ipynb 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3b7a290f",
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "<interactive>:1:1: error: Variable not in scope: foo"
     ]
    }
   ],
   "source": [
    "foo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "018d1386",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Haskell",
   "language": "haskell",
   "name": "haskell"
  },
  "language_info": {
   "codemirror_mode": "ihaskell",
   "file_extension": ".hs",
   "mimetype": "text/x-haskell",
   "name": "haskell",
   "pygments_lexer": "Haskell",
   "version": "8.10.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
vaibhavsagar@nixos-t480:~/repos/IHaskell$ $(nix-build release-8.10.nix)/bin/jupyter execute Foo.ipynb 
[NbClientApp] Executing Foo.ipynb
[NbClientApp] Executing notebook with kernel: haskell
Press Ctrl-C again to quit kernel.
vaibhavsagar@nixos-t480:~/repos/IHaskell$ echo $?
0
```

This definitely used to work (as evidenced by https://github.com/gibiansky/IHaskell/blob/6362b9b1d68e347749792c783b6bc12a33600d07/test/acceptance.nbconvert.sh#L31) so I suspect something has changed in Jupyter.

**Comment by FPtje** [comment]
Thanks for creating a separate issue.

When creating an equivalent notebook in Python, there are some minor differences:

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5dde2a80-ef22-426f-b9ff-ac155b78d2d0",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'foo' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_9622/156288784.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mfoo\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m: name 'foo' is not defined"
     ]
    }
   ],
   "source": [
    "foo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d14f949-1876-42e9-b8bf-baabb81f9e80",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

In the Python notebook, `ename` and `evalue` have a non-empty string, whereas in the IHaskell notebook, they have empty strings. Though it would be surprising if that would cause the issue. After all, `output_type` is set to `error` 🤔

This is the output of running the Python notebook:

```bash
$ jupyter execute foo-python.ipynb 
[NbClientApp] Executing foo-python.ipynb
[NbClientApp] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/nix/store/wbj1yj1ysalvczz81zq6v5psnlqa3nzm-python3.8-nbclient-0.5.9/bin/.jupyter-execute-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/cli.py", line 113, in initialize
    [self.run_notebook(path) for path in self.notebooks]
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/cli.py", line 113, in <listcomp>
    [self.run_notebook(path) for path in self.notebooks]
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/cli.py", line 154, in run_notebook
    client.execute()
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/nix/store/x0yzsy3pk7qvvw1x6igaifqr1434isqk-python3-3.8.12/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/nix/store/imqazsdd1wzg5xi1909jvksz1gj1vk7q-python3-3.8.12-env/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
foo
------------------

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_10473/156288784.py in <module>
----> 1 foo

NameError: name 'foo' is not defined
NameError: name 'foo' is not defined
```

I'm not very knowledgeable on how Jupyter interacts with kernels, but perhaps the above data combined with the equivalent behavior in IHaskell can provide a clue.

**Comment by vaibhavsagar** [comment]
Embarrassingly, I am the one who wrote the code that is setting `ename` and `evalue` to empty strings (https://github.com/gibiansky/IHaskell/pull/1008), but I don't think that is the issue, since I changed the offending line:

```diff
diff --git a/src/IHaskell/Publish.hs b/src/IHaskell/Publish.hs
index 968d8e1..eff00f7 100644
--- a/src/IHaskell/Publish.hs
+++ b/src/IHaskell/Publish.hs
@@ -76,7 +76,8 @@ publishResult send replyHeader displayed updateNeeded poutput upager result succ
         send $ PublishDisplayData hdr (map (makeUnique uniqueLabel . prependCss) outs) Nothing
       Failure -> do
         hdr <- dupHeader replyHeader ExecuteErrorMessage
-        send $ ExecuteError hdr [T.pack (extractPlain outs)] "" ""
+        let errorMessage = T.pack (extractPlain outs)
+        send $ ExecuteError hdr [errorMessage] "error" errorMessage
```

 and saw the same result:

```shell
vaibhavsagar@nixos-t480:~/repos/IHaskell$ cat Foo.ipynb 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3b7a290f",
   "metadata": {},
   "outputs": [
    {
     "ename": "error",
     "evalue": "<interactive>:1:1: error: Variable not in scope: foo",
     "output_type": "error",
     "traceback": [
      "<interactive>:1:1: error: Variable not in scope: foo"
     ]
    }
   ],
   "source": [
    "foo"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Haskell",
   "language": "haskell",
   "name": "haskell"
  },
  "language_info": {
   "codemirror_mode": "ihaskell",
   "file_extension": ".hs",
   "mimetype": "text/x-haskell",
   "name": "haskell",
   "pygments_lexer": "Haskell",
   "version": "8.10.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
vaibhavsagar@nixos-t480:~/repos/IHaskell$ result/bin/jupyter execute Foo.ipynb 
[NbClientApp] Executing Foo.ipynb
[NbClientApp] Executing notebook with kernel: haskell
Press Ctrl-C again to quit kernel.
vaibhavsagar@nixos-t480:~/repos/IHaskell$ echo $?
0
```

Incidentally, that PR is where we added support for the `error` cell type, so I know it was working at that point and now I'm even more convinced that something has changed in Jupyter in the meantime. Of course if this is true we would still need to adapt to this change on our end, but I'm not sure how to proceed from here.

**Comment by FPtje** [comment]
Thanks for looking into it. 
I've done some dirty debugging. I've added debug prints in `_check_raise_for_error` in `nbclient`'s `client.py` as follows:

```python
    def _check_raise_for_error(self, cell: NotebookNode, exec_reply: t.Optional[t.Dict]) -> None:
        self.log.debug("CHECK RAISE FOR ERROR")
        if exec_reply is None:
            self.log.debug("exec_reply is none")
            return None

        exec_reply_content = exec_reply['content']
        if exec_reply_content['status'] != 'error':
            self.log.debug("status is not error %s", exec_reply_content['status'])
            return None

        cell_allows_errors = (not self.force_raise_errors) and (
            self.allow_errors
            or exec_reply_content.get('ename') in self.allow_error_names
            or "raises-exception" in cell.metadata.get("tags", [])
        )

        self.log.debug("right before raise")
        if cell_allows_errors:
            self.log.debug("allows errors!")
        if not cell_allows_errors:
            self.log.debug("Should raise!")
            raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
```

The result is as follows:
```
$ /nix/store/jcswgmyzplg9kc64lq4bmdvslamw1d1a-ihaskell-with-packages/bin/jupyter-execute --NbClientApp.log_level DEBUG foo-haskell.ipynb
[NbClientApp] Searching ['/home/falco.peijnenburg/Programs/IHaskell', '/home/falco.peijnenburg/.jupyter', '/nix/store/wyppix82vblc8izsdsvv0l84zmr773yv-python3-3.9.9-env/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbClientApp] Looking for jupyter_config in /etc/jupyter
[NbClientApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbClientApp] Looking for jupyter_config in /nix/store/wyppix82vblc8izsdsvv0l84zmr773yv-python3-3.9.9-env/etc/jupyter
[NbClientApp] Looking for jupyter_config in /home/falco.peijnenburg/.jupyter
[NbClientApp] Looking for jupyter_config in /home/falco.peijnenburg/Programs/IHaskell
[NbClientApp] Looking for jupyter_execute_config in /etc/jupyter
[NbClientApp] Looking for jupyter_execute_config in /usr/local/etc/jupyter
[NbClientApp] Looking for jupyter_execute_config in /nix/store/wyppix82vblc8izsdsvv0l84zmr773yv-python3-3.9.9-env/etc/jupyter
[NbClientApp] Looking for jupyter_execute_config in /home/falco.peijnenburg/.jupyter
[NbClientApp] Looking for jupyter_execute_config in /home/falco.peijnenburg/Programs/IHaskell
[NbClientApp] Executing foo-haskell.ipynb
[NbClientApp] Instantiating kernel 'Haskell' with kernel provisioner: local-provisioner
[NbClientApp] Starting kernel: ['/nix/store/qni7syxhy0rdi1sf8shqbkvz4zkqw14d-ihaskell/bin/ihaskell', 'kernel', '/tmp/nix-shell.jUaqTi/tmpfdxdg43m.json', '+RTS', '-M3g', '-N2', '-RTS']
[NbClientApp] Connecting to: tcp://127.0.0.1:48935
[NbClientApp] connecting iopub channel to tcp://127.0.0.1:41615
[NbClientApp] Connecting to: tcp://127.0.0.1:41615
[NbClientApp] connecting shell channel to tcp://127.0.0.1:60653
[NbClientApp] Connecting to: tcp://127.0.0.1:60653
[NbClientApp] connecting stdin channel to tcp://127.0.0.1:41723
[NbClientApp] Connecting to: tcp://127.0.0.1:41723
[NbClientApp] connecting heartbeat channel to tcp://127.0.0.1:51217
[NbClientApp] connecting control channel to tcp://127.0.0.1:48935
[NbClientApp] Connecting to: tcp://127.0.0.1:48935
[NbClientApp] Executing notebook with kernel: haskell
[NbClientApp] Executing cell:
foo
[NbClientApp] msg_type: status
[NbClientApp] content: {'execution_state': 'busy'}
[NbClientApp] msg_type: execute_input
[NbClientApp] content: {'execution_count': 1, 'code': 'foo'}
[NbClientApp] msg_type: error
[NbClientApp] content: {'traceback': ['<interactive>:1:1: error: Variable not in scope: foo'], 'ename': '', 'evalue': ''}
[NbClientApp] msg_type: status
[NbClientApp] content: {'execution_state': 'idle'}
[NbClientApp] CHECK RAISE FOR ERROR
[NbClientApp] status is not error ok
[NbClientApp] Skipping non-executing cell 1
Press Ctrl-C again to quit kernel.
```

The crucial debug message here is `[NbClientApp] status is not error ok`. Apparently the Kernel at some point returns a reply with status `ok`, where it should return with status `error`. The IHaskell data type appears to be `ExecuteReplyStatus`. The code returning Ok appears to be here:

https://github.com/gibiansky/IHaskell/blob/b73a82804e2b9871c42a0fcf994cb4e52a4a45f6/main/Main.hs#L318-L324

I reckon the `evaluate` function might have to be refactored a bit to return the evaluation status of the given code. When parsing or evaluation failed, the returned `ExecuteReply` should have `status = Err`.

**Comment by FPtje** [comment]
I've created a pull request with a fix here: https://github.com/gibiansky/IHaskell/pull/1319
