### ISSUE TITLE
IPython notebook error when running under Python 3

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#73]
When running IHaskell in a Python 3.3 environment, IHaskell notebook boots OK, but gives the following error when I try to open a notebook:

```
2014-01-02 16:45:00.679 [tornado.access] 200 GET /api/notebooks/haskell%20stats.ipynb?_=1388699099579 (127.0.0.1) 2.86ms
2014-01-02 16:45:01.223 [NotebookApp] ERROR | Unhandled error in API request
Traceback (most recent call last):
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 294, in __get__
    value = obj._trait_values[self.name]
KeyError: 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 1012, in validate
    return bytes(value)
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/html/base/handlers.py", line 276, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/html/services/sessions/handlers.py", line 65, in post
    kernel_id = km.start_kernel(cwd=nbm.get_os_path(path))
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/html/services/kernels/kernelmanager.py", line 60, in start_kernel
    kernel_id = super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/kernel/multikernelmanager.py", line 116, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/kernel/manager.py", line 202, in start_kernel
    self.write_connection_file()
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/kernel/connect.py", line 477, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 298, in __get__
    value = obj._trait_dyn_inits[self.name](obj)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/kernel/manager.py", line 59, in _session_default
    return Session(parent=self)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/kernel/zmq/session.py", line 419, in __init__
    super(Session, self).__init__(**kwargs)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/config/configurable.py", line 99, in __init__
    self.config = config
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 320, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 469, in _notify_trait
    c(name, old_value, new_value)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/config/configurable.py", line 175, in _config_changed
    self._load_config(new, traits=traits, section_names=section_names)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/config/configurable.py", line 159, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 316, in __set__
    new_value = self._validate(obj, value)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 324, in _validate
    return self.validate(obj, value)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 1014, in validate
    self.error(obj, value)
  File "/Users/Stian/.py3/lib/python3.3/site-packages/IPython/utils/traitlets.py", line 347, in error
    raise TraitError(e)
IPython.utils.traitlets.TraitError: The 'key' trait of a Session instance must be a bytes object, but a value of '' <class 'str'> was specified.
```

When I run IHaskell in a Python 2 mode, it works fine. This seems to be a classic Python 2 vs 3 problem, however it does not show up when I run ipython notebook under Python 3 (I've been using that for a while without problems). 

Not a big issue, but perhaps worth noting in the installation instructions. I'm not sure if this is an actual IPython bug that it's worth passing "upstream", or if there is something about how IHaskell does things?

**Comment by rileyjbauer** [comment]
This was resolved for me by changing the --Session.key value from `""` to `b'""'` as suggested here:
https://github.com/ipython/ipykernel/issues/258
