### ISSUE TITLE
Followed install instructions, "run" then fails with a Python import error

### ISSUE THREAD

**Issue by Peaker** [gibiansky/IHaskell#822]
```stack exec jupyter -- notebook```

Results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.5/dist-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'
```

**Comment by vaibhavsagar** [comment]
Are you running the most recent `jupyter_core`? See https://github.com/jupyter/notebook/issues/3242 and https://stackoverflow.com/questions/48372019/importerror-cannot-import-name-ensure-dir-exists

**Comment by Peaker** [comment]
The one pip installed from your requirements.txt as per the instructions.

I think the requirements.txt need to be updated.

**Comment by vaibhavsagar** [comment]
Sure, done.
