### ISSUE TITLE
Traceback error while running install_c_kernel

### ISSUE THREAD

**Issue by utkarsh2102** [gibiansky/IHaskell#949]
I'm using `Python 3.7.0` and while following the installation steps, I ran `install_c_kernel` and ran into a Traceback error.

```
Traceback (most recent call last):
  File "/usr/bin/install_c_kernel", line 9, in <module>
    from IPython.utils.tempdir import TemporaryDirectory
  File "/usr/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/usr/lib/python3.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 22, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```

I tried fixing the dependencies, yet no fixes.

**Comment by vaibhavsagar** [comment]
Where do we require `install_c_kernel`? This looks like a Jupyter installation issue rather than something to do with IHaskell.

**Comment by vaibhavsagar** [comment]
Closing this, please reopen if necessary.
